idz/Controllers/НомераController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using idz.Models;

namespace idz.Controllers
{
    public class НомераController : Controller
    {

        private PetsContextDB db = new PetsContextDB();
        // GET: Номера
        public ActionResult Index(string pet)
        {
           

            List<Номера_с> номер =
                (from n in db.Номера
                 join v in db.Виды_животного on n.Код_вида equals v.Код_вида
                 join tn in db.Типы_номеров on n.Код_типа_номера equals tn.Код_типа_номера

                 select new Номера_с
                 {  Image = n.Image,
                     Номер = n.Код_номера,
                     Стоимость = n.Стоимость.Value,
                     Количество_мест = n.Количество_мест,
                     Животное = v.Наименование,
                     Тип_номера = tn.Наименование,
                     Количество_заказов = (from z in db.Заказы
                                           where z.Код_номера == n.Код_номера
                                           select new { z.Номер_заказа}).Count()
                  }).ToList();


            if (pet != null && !pet.Equals("Все"))
            {
                номер = номер.Where(p => p.Животное == pet).ToList();
            }


            var животные =
           (from s in db.Виды_животного
            select new
            {
               Животное = s.Наименование
            }).ToList();
            животные.Insert(0, new { Животное = "Все" });

            Номера_с N = new Номера_с
            {
                НомераДляВыбора = номер.ToList(),
                СписокВыбораЖивотных = new SelectList(животные, "Животное", "Животное")

            };

            return View(N);
        }
    

        public ActionResult Create()
        {
            var номер = new Номера_с
            {
                СписокЖивотных = db.Виды_животного.ToList()
                    .Select(и => new SelectListItem()
                    {
                        Text = и.Наименование,
                        Value = и.Код_вида.ToString()
                    })
                    .ToList(),
                СписокНомеров = db.Типы_номеров.ToList()
                    .Select(и => new SelectListItem()
                    {
                        Text = и.Наименование,
                        Value = и.Код_типа_номера.ToString()
                    })
                    .ToList(),
            };
            return View(номер);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Номера_с n, HttpPostedFileBase uploadImage)
        {
            byte[] imageData = null;
            // считываем переданный файл в массив байтов
            using (var binaryReader = new BinaryReader(uploadImage.InputStream))
            {
                imageData = binaryReader.ReadBytes(uploadImage.ContentLength);
            }

            var новый_номер = new Номер_гостиницы
            {
                //Код_номера = ,
                Количество_мест = n.Количество_мест,
                Стоимость = n.Стоимость,
                Код_вида = n.ID_вида,
                Код_типа_номера = n.ID_типа_н,
                Image = imageData
            };
            db.Номера.Add(новый_номер);

            db.SaveChanges();
            return RedirectToAction("Index");
        }



        public ActionResult Edit(int? id)
        {

            var номер_на_изменение = db.Номера.Find(id);
            List<SelectListItem> СписокЖивотныхБД = db.Виды_животного.ToList()
                .Select(и => new SelectListItem()
                {
                    Text = и.Наименование,
                    Value = и.Код_вида.ToString(),
                    Selected = и.Код_вида == номер_на_изменение.Код_вида
                })
                .ToList();
            List<SelectListItem> СписокНомеровБД = db.Типы_номеров.ToList()
                .Select(к => new SelectListItem()
                {
                    Text = к.Наименование,
                    Value = к.Код_типа_номера.ToString(),
                    Selected = к.Код_типа_номера == номер_на_изменение.Код_типа_номера

                })
                .ToList();

            var номер_для_изм = new Номера_с
            {    Номер= номер_на_изменение.Код_номера,
                ID_типа_н = номер_на_изменение.Код_типа_номера,
                ID_вида = номер_на_изменение.Код_вида,
                Количество_мест = номер_на_изменение.Количество_мест,
                Стоимость = номер_на_изменение.Стоимость.Value,
                СписокЖивотных = СписокЖивотныхБД,
                СписокНомеров = СписокНомеровБД,
                Image=номер_на_изменение.Image
            };
          
            return View(номер_для_изм);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Номера_с номер_для_изм, HttpPostedFileBase uploadImage)

        {
            byte[] imageData = null;
            // считываем переданный файл в массив байтов
            using (var binaryReader = new BinaryReader(uploadImage.InputStream))
            {
                imageData = binaryReader.ReadBytes(uploadImage.ContentLength);
            }


            var номерНовый = db.Номера.Find(номер_для_изм.Номер);
            номерНовый.Стоимость = номер_для_изм.Стоимость;
            номерНовый.Количество_мест = номер_для_изм.Количество_мест;
            номерНовый.Код_вида = номер_для_изм.ID_вида;
            номерНовый.Код_типа_номера = номер_для_изм.ID_типа_н;
            номерНовый.Image = imageData;
            //db.SaveChanges();
            //return RedirectToAction("Index");

            if (ModelState.IsValid)
            {
                db.Entry(номерНовый).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            //ViewBag.ID_персоны = new SelectList(db.Игроки, "ID_персоны", "ID_персоны", контракт_игрока_с_клубом.ID_персоны);
            // ViewBag.ID_клуба = new SelectList(db.Клубы, "ID_клуба", "Название", контракт_игрока_с_клубом.ID_клуба);
            //ViewBag.ID_позиции = new SelectList(db.Позиции_игроков, "ID_позиции", "Название", контракт_игрока_с_клубом.ID_позиции);
            return View(номер_для_изм);


            //ViewBag.ID_персоны = new SelectList(db.Игроки, "ID_персоны", "ID_персоны", контракт_игрока_с_клубом.ID_персоны);
            // ViewBag.ID_клуба = new SelectList(db.Клубы, "ID_клуба", "Название", контракт_игрока_с_клубом.ID_клуба);
            //ViewBag.ID_позиции = new SelectList(db.Позиции_игроков, "ID_позиции", "Название", контракт_игрока_с_клубом.ID_позиции);
            //return View(контрактИгрока);
        }
    }
}

idz/Views/Номера/Create.cshtml
@model idz.Models.Номера_с
@{
    ViewBag.Title = "Create";
   // Layout = "Create";
}

@*<h2>View</h2>*@
@using (Html.BeginForm("Create", "Номера", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Новый номер</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.LabelFor(model => model.Стоимость, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Стоимость, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Стоимость, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Количество_мест, "Количество мест", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Количество_мест, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Количество_мест, "", new { @class = "text-danger" })
        </div>
    </div>


    <div class="form-group">
        @Html.LabelFor(model => model.СписокНомеров, "Номера", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ID_типа_н", Model.СписокНомеров, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ID_типа_н, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.СписокЖивотных, "Животное", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ID_вида", Model.СписокЖивотных, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ID_вида, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="editor-label">Файл изображения</div>
        <div class="editor-field">
            <input type="file" name="uploadImage" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Создать" class="btn btn-outline-info" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

idz/Views/Номера/Edit.cshtml
@model idz.Models.Номера_с

@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@*<h2>Изменение</h2>*@


@using (Html.BeginForm("Edit", "Номера", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Изменение информации о номере</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Номер)

    <div class="form-group">
        @Html.LabelFor(model => model.Стоимость, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Стоимость, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Стоимость, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Количество_мест, "Количество мест", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.Количество_мест, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.Количество_мест, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.СписокНомеров, "Номера", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ID_типа_н", Model.СписокНомеров, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ID_типа_н, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.СписокЖивотных, "Животное", htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.DropDownList("ID_вида", Model.СписокЖивотных, htmlAttributes: new { @class = "form-control" })
            @Html.ValidationMessageFor(model => model.ID_вида, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Raw("<img style='width:140px; height:100px;' src=\"data:image/jpeg;base64,"
                                      + Convert.ToBase64String(Model.Image) + "\" />")
    </div>

    <div class="form-group">
        <div class="editor-label">Файл изображения</div>
        <div class="editor-field">
            <input type="file" name="uploadImage" />
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Сохранить" class="btn btn-outline-info" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

idz/Views/Номера/index.cshtml
@model idz.Models.Номера_с

@{
    ViewBag.Title = "index";
}

<h3>Номера гостиницы</h3>
@if (User.IsInRole("admin"))
{
<button type="button" class="btn btn-outline-secondary m-2">
    @Html.ActionLink("Добавить номер", "Create")
</button>
   
}

<form method="get" style="margin-bottom: 20px;">
    <div class="form-inline m-2">
        <label class="control-label">Питомец:&nbsp </label>
        @Html.DropDownList("pet", Model.СписокВыбораЖивотных as SelectList,
                    htmlAttributes: new { @class = "form-control" })

        <input type="submit" value="Показать" class="btn btn-outline-info" />
    </div>
</form>


<div class="container-fluid">
    <div class="row ">
        @foreach (var item in Model.НомераДляВыбора)
        {

        <div class="col-md-6 mb-2">
            <p class="rounded">
                @Html.Raw("<img style='width:350px; height:250px;' src=\"data:image/jpeg;base64,"
                                      + Convert.ToBase64String(item.Image) + "\" />")
            </p>

            <table class="table table-hover">
                <tr>
                    <td>
                        Номер
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Номер)
                    </td>
                </tr>
                <tr>
                    <td>
                        Тип номера
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Тип_номера)
                    </td>
                </tr>
                <tr>
                    <td>
                        Количество мест
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Количество_мест)
                    </td>
                </tr>
                <tr>
                    <td>
                        Стоимость
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Стоимость)
                    </td>
                </tr>
                <tr>
                    <td>
                        Для кого
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Животное)
                    </td>
                </tr>
                <tr>
                    <td>
                        Был заказан
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.Количество_заказов)
                    </td>
                </tr>
            </table>
            @if (User.IsInRole("admin"))
            {
                <button type="button" class="btn btn-outline-secondary">
                    @Html.ActionLink("Изменить", "Edit", new { id = item.Номер })
                </button>
            }
            </div>

        }
    </div>
</div>