idz/Controllers/ConsoleController.cs
using idz.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace idz.Controllers
{
    public class ConsoleController : Controller
    {
        private PetsContextDB db = new PetsContextDB();
        // GET: Console
        public ActionResult Index(string US)
        {
            List<User_Cons> user =
               (from n in db.Users
                join v in db.Roles on n.RoleId equals v.Id
               orderby v.Name
            

                select new User_Cons
                {
                    Id = n.Id,
                    Email = n.Email,
                    Password = n.Password,
                    Role = v.Name
                  
                }).ToList();
            if (US != null && !US.Equals("Все"))
            {
                user = user.Where(p => p.Role == US).ToList();
            }
            var us11 =
         (from s in db.Roles
          select new
          {
              R = s.Name
          }).ToList();
            us11.Insert(0, new { R = "Все" });

            User_Cons N = new User_Cons
            {
               ДляВыбора = user.ToList(),
            СписокRole = new SelectList(us11, "R", "R")
            };

            return View(N);
        }

        public ActionResult Edit(int? id)
        {

            var пользователь = db.Users.Find(id);
            List<SelectListItem> Roles = db.Roles.ToList()
                .Select(и => new SelectListItem()
                {
                    Text = и.Name,
                    Value = и.Id.ToString(),
                    Selected = и.Id == пользователь.RoleId
                })
                .ToList();
           

            var пользователь2 = new User_Cons
            {
                Id = пользователь.Id,
                Email = пользователь.Email,
                Password = пользователь.Password,
                ID_role=пользователь.RoleId,
                СписокРолей = Roles

            };

            return View(пользователь2);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(User_Cons us1)

        {
           

            var us2 = db.Users.Find(us1.Id);
           us2.Email = us1.Email;
            us2.Password = us1.Password;
            us2.RoleId = us1.ID_role;
           

            if (ModelState.IsValid)
            {
                db.Entry(us2).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }


            return View(us1);


        }

        public ActionResult Create()
        {
            var us1 = new User_Cons
            {
                СписокРолей = db.Roles.ToList()
                .Select(и => new SelectListItem()
                {
                    Text = и.Name,
                    Value = и.Id.ToString(),
                 
                })
                .ToList(),

            };
            return View(us1);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(User_Cons US)
        {
          

            var us2 = new User
            {    Email = US.Email,
            Password = US.Password,
            RoleId = US.ID_role

            };
            db.Users.Add(us2);

            db.SaveChanges();
            return RedirectToAction("Index");
        }


    }
}

idz/Views/Console/Create.cshtml
@model idz.Models.User_Cons
@{

}

<!DOCTYPE html>
@using (Html.BeginForm("Create", "Console", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Новый пользователь</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.СписокРолей, "Роль", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_role", Model.СписокРолей, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_role, "", new { @class = "text-danger" })
            </div>
        </div>
       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Создать" class="btn btn-outline-info" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

idz/Views/Console/Edit.cshtml
@model idz.Models.User_Cons
@{

}


@using (Html.BeginForm("Edit", "Console", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Изменение информации о пользователе</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.СписокРолей, "Роль", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_role", Model.СписокРолей, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_role, "", new { @class = "text-danger" })
            </div>
        </div>
       

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-outline-info" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

idz/Views/Console/Index.cshtml
@model idz.Models.User_Cons
@{

}

<!DOCTYPE html>

<button type="button" class="btn btn-outline-secondary m-2">
    @Html.ActionLink("Добавить пользователя", "Create")
</button>

<form method="get" style="margin-bottom: 20px;">
    <div class="form-inline m-2">
        <label class="control-label">Роль:&nbsp </label>
        @Html.DropDownList("US", Model.СписокRole as SelectList,
                    htmlAttributes: new { @class = "form-control" })

        <input type="submit" value="Показать" class="btn btn-outline-info" />
    </div>
</form>


<div class="container-fluid">
    <div class="row ">
        @foreach (var item in Model.ДляВыбора)
        {

            <div class="col-md-4 mb-2">

                <table class="table table-hover">
                    <tr>
                        <td>
                            Пользователь
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Email)
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Пароль
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Password)
                        </td>
                    </tr>
                    <tr>
                        <td>
                            Роль
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.Role)
                        </td>
                    </tr>



                </table>

                <button type="button" class="btn btn-outline-secondary">
                    @Html.ActionLink("Изменить", "Edit", new { id = item.Id })
                </button>

            </div>

        }
    </div>
</div>